<a href="https://colab.research.google.com/github/MiguelFigueroa02/MCPI_Student_Repo/blob/main/courses/1-Semester/fundamentals%20of%20statistics/Projects/Notebooks/Estad%C3%ADstica_Descriptiva_Visualizaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
  <img src="https://raw.githubusercontent.com/MiguelFigueroa02/MCPI_Student_Repo/refs/heads/main/images/logo.png"
       width="30%">
</p>

#Fundamentos de Estadística
---
**Profesor:** Dr. Daniel de La Rosa Gómez\
**Estudiante:** Miguel Figueroa Aguilar

## 1.Descripción Breve de la base.
---

### Nombre y Fuente:
---
En este caso elegí el Dataset relacionado con el cáncer de pulmón de pacientes de 60 países compartido en la plataforma de [Kaggle](https://www.kaggle.com/datasets/laxmikantaroy/lung-cancer-risk-factors-and-survival-dataset/data)\
Este agrupa información clínica, demográfica, genética y del diagnóstico y estilo de vida relacionada con el cáncer de pulmón.

### ¿Qué representan los datos?
---
- Cubre la información clínica relevante de los pacientes incluyendo antecedentes de tabaquismo, síntomas, etapa del cáncer, tratamiento y rango de supervivencia de cada paciente

### ¿Qué representa cada fila?
---
- Cada fila representa el registro de cada uno de los pacientes incluidos en el dataset para identificar las variables asociadas con su diagnóstico.

In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import plotly.express as px

In [56]:
#Establecemos un formato adecuado de visualización de los dataframe que extraigamos
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth',None)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

In [57]:
# El dataset se extrae de la plataforma de kaggle y se sube a un repositorio personal de github
url = 'https://raw.githubusercontent.com/MiguelFigueroa02/MCPI_Student_Repo/refs/heads/main/courses/1-Semester/fundamentals%20of%20statistics/Projects/Data/lung_cancer_dataset.csv'

response = requests.get(url)
if response.status_code == 200:
  print('Se accedió a dataset con éxito')
  df = pd.read_csv(url)

Se accedió a dataset con éxito

In [58]:
df.head()

,Patient_ID,Diagnosis_Year,Diagnosis_Date,WHO_Region,Country,Age,Age_Group,Gender,Smoking_Status,Cigarettes_Per_Day,Years_Smoking,Pack_Years,Secondhand_Smoke,Family_History,Occupational_Hazard,Air_Pollution_Exposure,Alcohol_Use,BMI,BMI_Category,Exercise_Frequency,Chronic_Lung_Disease,Asbestos_Exposure,Radon_Exposure,Previous_Cancer_History,Risk_Factor_Count,Genetic_Mutation,Coughing,Shortness_of_Breath,Chest_Pain,Coughing_Blood,Fatigue,Weight_Loss,Wheezing,Recurrent_Infections,Swallowing_Difficulty,Finger_Clubbing,Symptom_Count,Cancer_Type,NSCLC_Subtype,Cancer_Stage,Tumor_Size_cm,Metastasis,Diagnosis_Method,Treatment,Survival_Months,Survived
0,LC-0001,2020,2020-11-04,Western Pacific,China,46,40-49,Female,Current Smoker,28,28,39.20,Yes,No,No,Moderate,No Alcohol,29.60,Overweight,Low,Yes,No,No,No,2,No Mutation,Yes,Yes,Yes,No,No,Yes,No,No,Yes,No,5,NSCLC,Adenocarcinoma,Stage IV,6.40,Yes,MRI,Chemo + Radiation,4,No
1,LC-0002,2021,2021-12-09,Americas,Mexico,71,70-79,Male,Former Smoker,5,34,8.50,Yes,No,No,High,Heavy,31.30,Obese,Moderate,No,No,No,Yes,3,KRAS,Yes,Yes,No,No,Yes,No,Yes,No,Yes,No,5,NSCLC,Adenocarcinoma,Stage I,2.60,No,Biopsy,Surgery + Chemotherapy,76,Yes
2,LC-0003,2017,2017-04-05,Western Pacific,Japan,53,50-59,Female,Never Smoked,0,0,0.00,Yes,No,No,High,Moderate,25.80,Overweight,Low,No,No,No,No,2,KRAS,No,No,Yes,Yes,Yes,No,No,No,No,No,3,NSCLC,Squamous Cell,Stage I,2.90,No,LDCT Screening,Surgery,69,No
3,LC-0004,2018,2018-11-24,Western Pacific,Singapore,55,50-59,Male,Current Smoker,21,34,35.70,No,Yes,No,Moderate,No Alcohol,25.30,Overweight,Low,Yes,No,No,No,2,No Mutation,Yes,No,No,Yes,Yes,Yes,Yes,Yes,No,No,6,NSCLC,Adenocarcinoma,Stage IV,7.00,Yes,CT Scan,Chemotherapy,9,No
4,LC-0005,2024,2024-02-19,Western Pacific,Malaysia,54,50-59,Male,Never Smoked,0,0,0.00,No,No,Yes,High,No Alcohol,32.00,Obese,Low,Yes,No,No,Yes,4,KRAS,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,5,NSCLC,Adenocarcinoma,Stage III,5.80,No,Bronchoscopy,Immunotherapy,5,Yes

In [59]:
df.Diagnosis_Year = pd.to_datetime(df.Diagnosis_Year)
df.Diagnosis_Date = pd.to_datetime(df.Diagnosis_Date)

In [60]:
column_names = [f'`{column}`' for column in df.columns]
column_types = [f'`{df[column].dtype}`' for column in df.columns]
column_shapes = [len(df[column]) for column in df.columns]
column_na = [df[column].isna().sum() for column in df.columns]

In [61]:
df_analysis = pd.DataFrame({
    'Variable': column_names,
    'Tipos':column_types,
    'OObservaciones': column_shapes,
    })
# df_analysis.to_markdown(index=False)

In [62]:
print(f'La cantidad de variables son {len(df.columns)}')
print(f'La cantidad de observaciones son {df.shape[0]}')

La cantidad de variables son 46
La cantidad de observaciones son 2000

### Número de observaciones y variables
---
- El Dataset está compuesto por un total de 46 variables diferentes.
- Adicional, contiene la información de 2000 observaciones (Pacientes)\
A continuación se desglosa la información detallada de cada variable.

| Variable                   | Tipos     |   Observaciones | Descripción |
|:-------------------------:|:---------:|:---------------:|:-----------:|
| `Patient_ID`              | `object`  |            2000 |Identificador único del paciente |
| `Diagnosis_Year`          | `datetime64[ns]`   |            2000 | Año en que el paciente fue diagnosticado |
| `Diagnosis_Date`          | `datetime64[ns]`  |            2000 | Fecha completa de diagnóstico (YYYY-MM-DD) |
| `WHO_Region`              | `object`  |            2000 | Región de la OMS (WHO) |
| `Country`                 | `object`  |            2000 | País de origen |
| `Age`                     | `int64`   |            2000 | Edad de los pacientes (años) |
| `Age_Group`               | `object`  |            2000 | Grupo de 10 años (ej. 40 - 49) al que pertenece el paciente. |
| `Gender`                  | `object`  |            2000 | Género (Másculino / Femenino) |
| `Smoking_Status`          | `object`  |            2000 | Estatus de fumador |
| `Cigarettes_Per_Day`      | `int64`   |            2000 | Cantidad promedio de cigarrillos consumidos diariamente |
| `Years_Smoking`           | `int64`   |            2000 | Años Fumando |
| `Pack_Years`              | `float64` |            2000 | Cantidad acumulada de humo de tabaco expuesto por año |
| `Secondhand_Smoke`        | `object`  |            2000 | ¿Fumador Pasivo? |
| `Family_History`          | `object`  |            2000 | ¿Antecedentes Familiares? |
| `Occupational_Hazard`     | `object`  |            2000 | ¿Peligro ocupacional? |
| `Air_Pollution_Exposure`  | `object`  |            2000 | Grado de Exposición a contaminación del aire |
| `Alcohol_Use`             | `object`  |            2000 | Nivel de uso de alcohol |
| `BMI`                     | `float64` |            2000 | Índice de Masa corporal |
| `BMI_Category`            | `object`  |            2000 | Categorá de IMC |
| `Exercise_Frequency`      | `object`  |            2000 | Frecuencia de Ejercicio |
| `Chronic_Lung_Disease`    | `object`  |            2000 | ¿Enfermedad crónica de los pulmones? |
| `Asbestos_Exposure`       | `object`  |            2000 | Exposición a asbestos? |
| `Radon_Exposure`          | `object`  |            2000 | ¿Exposición a Radón? |
| `Previous_Cancer_History` | `object`  |            2000 | ¿Historia previa de cáncer ? |
| `Risk_Factor_Count`       | `int64`   |            2000 | Conteo de factores de riesgo |
| `Genetic_Mutation`        | `object`  |            2000 | Mutación genética |
| `Coughing`                | `object`  |            2000 | ¿Tos? |
| `Shortness_of_Breath`     | `object`  |            2000 | ¿Falta de aire? |
| `Chest_Pain`              | `object`  |            2000 | ¿Dolor de pecho? |
| `Coughing_Blood`          | `object`  |            2000 | ¿Tose sangre? |
| `Fatigue`                 | `object`  |            2000 | ¿fatiga? |
| `Weight_Loss`             | `object`  |            2000 | ¿Pérdida de peso? |
| `Wheezing`                | `object`  |            2000 | ¿Silbido? |
| `Recurrent_Infections`    | `object`  |            2000 | ¿Infecciones recurrentes? |
| `Swallowing_Difficulty`   | `object`  |            2000 | ¿Dificultad para tragar? |
| `Finger_Clubbing`         | `object`  |            2000 | ¿Acropauia? |
| `Symptom_Count`           | `int64`   |            2000 | Conteo de síntomas |
| `Cancer_Type`             | `object`  |            2000 | Tipo de cáncer |
| `NSCLC_Subtype`           | `object`  |            2000 | Subtipo histológico |
| `Cancer_Stage`            | `object`  |            2000 | Etapa de cáncer |
| `Tumor_Size_cm`           | `float64` |            2000 | Tamaño de tumor (cm) |
| `Metastasis`              | `object`  |            2000 | Metástasis |
| `Diagnosis_Method`        | `object`  |            2000 | Método de diagnóstico |
| `Treatment`               | `object`  |            2000 | Tratamiento |
| `Survival_Months`         | `int64`   |            2000 | Meses de supervivencia |
| `Survived`                | `object`  |            2000 | ¿Sobrevivió? |

## 2.Identificación de los tipos de variables
---

In [96]:
categoricas = [col for col in df.columns if df[col].dtype == 'object']

In [97]:
ordinales = ['Age_Group','Smoking_Status','Air_Pollution_Exposure', 'Alcohol_Use','BMI_Category','Exercise_Frequency','Cancer_Stage']

In [98]:
nominales = [categorica for categorica in categoricas if categorica not in ordinales]

In [99]:
cuant_disc = []
cuant_cont = []

for col in df.columns:
  var_type = df[col].dtype
  if var_type == 'int64':
    cuant_disc.append(col)
  elif var_type == 'float64' or var_type == '<M8[ns]':
    cuant_cont.append(col)

### Variables cuantitativas
---

In [100]:
print('Las variables Cuantitativas Discretas son:\n-'+',\n-'.join(x.strip() for x in cuant_disc))

Las variables Cuantitativas Discretas son:
-Age,
-Cigarettes_Per_Day,
-Years_Smoking,
-Risk_Factor_Count,
-Symptom_Count,
-Survival_Months

In [68]:
print('Las variables Cuantitativas Continuas son:\n-'+',\n-'.join(x.strip() for x in cuant_cont))

Las variables Cuantitativas Continuas son:
-Diagnosis_Year,
-Diagnosis_Date,
-Pack_Years,
-BMI,
-Tumor_Size_cm

### Variables categóricas
---

In [69]:
print('Las variables Categóricas Ordinales son:\n-'+',\n-'.join(x.strip() for x in ordinales))

Las variables Categóricas Ordinales son:
-Age_Group,
-Smoking_Status,
-Air_Pollution_Exposure,
-Alcohol_Use,
-BMI_Category,
-Exercise_Frequency,
-Cancer_Stage

In [70]:
df[ordinales].describe()

,Age_Group,Smoking_Status,Air_Pollution_Exposure,Alcohol_Use,BMI_Category,Exercise_Frequency,Cancer_Stage
count,2000,2000,2000,2000,2000,2000,2000
unique,6,3,3,3,4,3,4
top,50-59,Never Smoked,Moderate,Moderate,Overweight,Low,Stage I
freq,657,1311,766,811,876,772,577

In [71]:
for ordinal in ordinales:
  print(f'Los valores únicos en la variable {ordinal} son:', ", ".join(f'{descr}' for descr in df[ordinal].unique()))
  print('--'*50)

Los valores únicos en la variable Age_Group son: 40-49, 70-79, 50-59, 80-89, 60-69, 30-39
----------------------------------------------------------------------------------------------------
Los valores únicos en la variable Smoking_Status son: Current Smoker, Former Smoker, Never Smoked
----------------------------------------------------------------------------------------------------
Los valores únicos en la variable Air_Pollution_Exposure son: Moderate, High, Low
----------------------------------------------------------------------------------------------------
Los valores únicos en la variable Alcohol_Use son: No Alcohol, Heavy, Moderate
----------------------------------------------------------------------------------------------------
Los valores únicos en la variable BMI_Category son: Overweight, Obese, Normal, Underweight
----------------------------------------------------------------------------------------------------
Los valores únicos en la variable Exercise_Frequency son: Low, Moderate, High
----------------------------------------------------------------------------------------------------
Los valores únicos en la variable Cancer_Stage son: Stage IV, Stage I, Stage III, Stage II
----------------------------------------------------------------------------------------------------

In [72]:
print('Las variables Categóricas Nominales son:\n-'+',\n-'.join(x.strip() for x in nominales))

Las variables Categóricas Nominales son:
-Patient_ID,
-WHO_Region,
-Country,
-Gender,
-Secondhand_Smoke,
-Family_History,
-Occupational_Hazard,
-Chronic_Lung_Disease,
-Asbestos_Exposure,
-Radon_Exposure,
-Previous_Cancer_History,
-Genetic_Mutation,
-Coughing,
-Shortness_of_Breath,
-Chest_Pain,
-Coughing_Blood,
-Fatigue,
-Weight_Loss,
-Wheezing,
-Recurrent_Infections,
-Swallowing_Difficulty,
-Finger_Clubbing,
-Cancer_Type,
-NSCLC_Subtype,
-Metastasis,
-Diagnosis_Method,
-Treatment,
-Survived

In [73]:
df[nominales].describe()

,Patient_ID,WHO_Region,Country,Gender,Secondhand_Smoke,Family_History,Occupational_Hazard,Chronic_Lung_Disease,Asbestos_Exposure,Radon_Exposure,Previous_Cancer_History,Genetic_Mutation,Coughing,Shortness_of_Breath,Chest_Pain,Coughing_Blood,Fatigue,Weight_Loss,Wheezing,Recurrent_Infections,Swallowing_Difficulty,Finger_Clubbing,Cancer_Type,NSCLC_Subtype,Metastasis,Diagnosis_Method,Treatment,Survived
count,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000
unique,2000,6,60,2,2,2,2,2,2,2,2,10,2,2,2,2,2,2,2,2,2,2,2,4,2,7,8,2
top,LC-1984,Western Pacific,Japan,Male,No,No,No,No,No,No,No,No Mutation,No,No,No,No,Yes,No,No,No,No,No,NSCLC,Adenocarcinoma,No,CT Scan,Surgery,No
freq,1,631,74,1248,1050,1483,1572,1624,1886,1847,1881,729,1024,1134,1292,1544,1323,1333,1448,1403,1717,1752,1771,1109,1441,590,410,1244

### Evaluación de datos faltantes o características importantes de la base.
---

In [74]:
disponible = df.notna().sum()
cantidad_nulos = df.isnull().sum()
porc_na = df.isna().mean()*100
vacios = (df == "").sum() | (df.apply(lambda x: str(x).isspace() if isinstance(x,str) else False)).sum()

calidad = pd.DataFrame({
    'n_disponible': disponible,
    'n_nulos': cantidad_nulos,
    '%_Valores_NA':porc_na,
    'n_vacios':vacios
})
calidad['%_Valores_NA'] = calidad['%_Valores_NA'].apply(lambda x: f'{x:.2%}')
calidad

                         n_disponible  n_nulos %_Valores_NA  n_vacios
Patient_ID                       2000        0        0.00%         0
Diagnosis_Year                   2000        0        0.00%         0
Diagnosis_Date                   2000        0        0.00%         0
WHO_Region                       2000        0        0.00%         0
Country                          2000        0        0.00%         0
Age                              2000        0        0.00%         0
Age_Group                        2000        0        0.00%         0
Gender                           2000        0        0.00%         0
Smoking_Status                   2000        0        0.00%         0
Cigarettes_Per_Day               2000        0        0.00%         0
Years_Smoking                    2000        0        0.00%         0
Pack_Years                       2000        0        0.00%         0
Secondhand_Smoke                 2000        0        0.00%         0
Family_History                   2000        0        0.00%         0
Occupational_Hazard              2000        0        0.00%         0
Air_Pollution_Exposure           2000        0        0.00%         0
Alcohol_Use                      2000        0        0.00%         0
BMI                              2000        0        0.00%         0
BMI_Category                     2000        0        0.00%         0
Exercise_Frequency               2000        0        0.00%         0
Chronic_Lung_Disease             2000        0        0.00%         0
Asbestos_Exposure                2000        0        0.00%         0
Radon_Exposure                   2000        0        0.00%         0
Previous_Cancer_History          2000        0        0.00%         0
Risk_Factor_Count                2000        0        0.00%         0
Genetic_Mutation                 2000        0        0.00%         0
Coughing                         2000        0        0.00%         0
Shortness_of_Breath              2000        0        0.00%         0
Chest_Pain                       2000        0        0.00%         0
Coughing_Blood                   2000        0        0.00%         0
Fatigue                          2000        0        0.00%         0
Weight_Loss                      2000        0        0.00%         0
Wheezing                         2000        0        0.00%         0
Recurrent_Infections             2000        0        0.00%         0
Swallowing_Difficulty            2000        0        0.00%         0
Finger_Clubbing                  2000        0        0.00%         0
Symptom_Count                    2000        0        0.00%         0
Cancer_Type                      2000        0        0.00%         0
NSCLC_Subtype                    2000        0        0.00%         0
Cancer_Stage                     2000        0        0.00%         0
Tumor_Size_cm                    2000        0        0.00%         0
Metastasis                       2000        0        0.00%         0
Diagnosis_Method                 2000        0        0.00%         0
Treatment                        2000        0        0.00%         0
Survival_Months                  2000        0        0.00%         0
Survived                         2000        0        0.00%         0

#### Interpretación
---
- El Dataset obtenido no presenta datos faltantes lo cual indica que todos los pacientes registrados cuentan con registro en todas las variables.
- El análisis estadístico puede aplicarse a todas las variables, el cual variará dependiendo del tipo de variable estadística.

## 3.Evaluación Datos Cuantitativos
---

In [93]:
def cuantitativo(columna):
  print(f'Se selecciona la variable cuantitativa {columna}:\n')
  print('--'*25)

  col = df[columna]
  q1 = col.quantile(0.25)
  print(f'- Resultados del primer cuartil (Q1):  {q1}\n')
  q3 = col.quantile(0.75)
  print(f'- Resultados del tercer cuartil (Q3):  {q3}\n')
  iqr = q3 - q1
  print(f'- Rango Intercuartil (IQR):  {iqr}')
  print('--'*25)

  lim_inf = q1 - (1.5 * iqr)
  atipicos_li = df[(df[columna] < lim_inf)][['Patient_ID',columna, 'Age_Group','Country','Cancer_Type','Survived']].set_index(['Patient_ID'])
  print(f'Límite inferior conforme a regla del rango IQR (1.5 veces IQR):  {lim_inf:.2f}')
  cant_atip_li = len(atipicos_li)
  print(f'Cantidad de resultados atípicos debajo de rango 1.5 veces IQR: {cant_atip_li}')
  if cant_atip_li > 0:
    print(atipicos_li.sort_values(columna,ascending=False).to_markdown())
  print('--'*25)

  mediana = col.median()
  print(f'Valor de mediana: {mediana}')
  media = col.mean()
  print(f'Valor de media: {media:.2f}')
  dev_est = col.std()
  print(f'Desviación Estándar: {dev_est:.2f}')
  print('--'*25)

  lim_sup = q3 + (1.5 * iqr)
  atipicos_su = df[(df[columna] > lim_sup)][['Patient_ID',columna, 'Age_Group','Country','Cancer_Type','Survived']].set_index(['Patient_ID'])
  print(f'Límite superior conforme a regla del rango IQR (1.5 veces IQR):  {lim_sup:.2f}')
  cant_atip_su = len(atipicos_su)
  print(f'Cantidad de resultados atípicos superiores a rango 1.5 veces IQR: {cant_atip_su}')
  if cant_atip_su > 0:
    print(atipicos_su.sort_values(columna,ascending=True).to_markdown())

In [94]:
cuantitativo('Cigarettes_Per_Day')

Se selecciona la variable cuantitativa Cigarettes_Per_Day:

--------------------------------------------------
- Resultados del primer cuartil (Q1):  0.0

- Resultados del tercer cuartil (Q3):  14.0

- Rango Intercuartil (IQR):  14.0
--------------------------------------------------
Límite inferior conforme a regla del rango IQR (1.5 veces IQR):  -21.00
Cantidad de resultados atípicos debajo de rango 1.5 veces IQR: 0
--------------------------------------------------
Valor de mediana: 0.0
Valor de media: 7.27
Desviación Estándar: 11.67
--------------------------------------------------
Límite superior conforme a regla del rango IQR (1.5 veces IQR):  35.00
Cantidad de resultados atípicos superiores a rango 1.5 veces IQR: 59
| Patient_ID   |   Cigarettes_Per_Day | Age_Group   | Country      | Cancer_Type   | Survived   |
|:-------------|---------------------:|:------------|:-------------|:--------------|:-----------|
| LC-0037      |                   36 | 60-69       | Mongolia     | NSCLC         | No         |
| LC-0207      |                   36 | 30-39       | New Zealand  | SCLC          | No         |
| LC-0254      |                   36 | 50-59       | Japan        | NSCLC         | No         |
| LC-0267      |                   36 | 60-69       | Philippines  | NSCLC         | No         |
| LC-0341      |                   36 | 50-59       | Sweden       | NSCLC         | No         |
| LC-0374      |                   36 | 60-69       | Malaysia     | NSCLC         | No         |
| LC-0483      |                   36 | 50-59       | Cuba         | SCLC          | No         |
| LC-0407      |                   36 | 60-69       | Australia    | NSCLC         | No         |
| LC-1898      |                   36 | 60-69       | Malaysia     | NSCLC         | No         |
| LC-1604      |                   36 | 70-79       | Oman         | NSCLC         | No         |
| LC-1780      |                   36 | 50-59       | Maldives     | NSCLC         | No         |
| LC-0842      |                   37 | 50-59       | Peru         | NSCLC         | No         |
| LC-0978      |                   37 | 70-79       | Uganda       | SCLC          | No         |
| LC-0772      |                   37 | 40-49       | Netherlands  | SCLC          | No         |
| LC-0145      |                   37 | 60-69       | China        | NSCLC         | No         |
| LC-1477      |                   37 | 50-59       | Bangladesh   | NSCLC         | No         |
| LC-1139      |                   37 | 50-59       | Netherlands  | SCLC          | No         |
| LC-1219      |                   37 | 50-59       | Sweden       | SCLC          | No         |
| LC-1232      |                   37 | 70-79       | Russia       | NSCLC         | No         |
| LC-1997      |                   37 | 50-59       | Brazil       | SCLC          | No         |
| LC-1338      |                   37 | 70-79       | Sri Lanka    | NSCLC         | Yes        |
| LC-0949      |                   38 | 60-69       | Malaysia     | NSCLC         | No         |
| LC-1484      |                   38 | 60-69       | Cuba         | NSCLC         | No         |
| LC-0544      |                   38 | 70-79       | Maldives     | NSCLC         | No         |
| LC-0733      |                   38 | 70-79       | Argentina    | NSCLC         | No         |
| LC-0425      |                   38 | 40-49       | Germany      | NSCLC         | No         |
| LC-0621      |                   38 | 60-69       | UK           | NSCLC         | Yes        |
| LC-0106      |                   38 | 40-49       | Tanzania     | NSCLC         | Yes        |
| LC-0219      |                   38 | 60-69       | Peru         | NSCLC         | No         |
| LC-0415      |                   38 | 50-59       | France       | NSCLC         | Yes        |
| LC-0814      |                   39 | 70-79       | Malaysia     | NSCLC         | No         |
| LC-0656      |                   39 | 50-59       | Australia    | NSCLC         | Yes        |
| LC-1292      |                   39 | 50-59       | Bangladesh   | SCLC          | No         |
| LC-1823      |                   39 | 80-89       | UK           | SCLC          | Yes        |
| LC-1676      |                   39 | 50-59       | Singapore    | NSCLC         | No         |
| LC-0034      |                   39 | 60-69       | Vietnam      | NSCLC         | Yes        |
| LC-1844      |                   39 | 40-49       | Iran         | NSCLC         | No         |
| LC-1290      |                   40 | 50-59       | Turkey       | NSCLC         | No         |
| LC-0120      |                   40 | 80-89       | Venezuela    | NSCLC         | No         |
| LC-1508      |                   40 | 50-59       | Uganda       | NSCLC         | No         |
| LC-0756      |                   41 | 70-79       | Colombia     | NSCLC         | No         |
| LC-0351      |                   41 | 50-59       | France       | NSCLC         | No         |
| LC-1445      |                   41 | 50-59       | Russia       | NSCLC         | No         |
| LC-1492      |                   41 | 60-69       | Kuwait       | SCLC          | No         |
| LC-0809      |                   41 | 40-49       | Jordan       | NSCLC         | No         |
| LC-0736      |                   42 | 40-49       | Saudi Arabia | NSCLC         | No         |
| LC-0394      |                   42 | 40-49       | Chile        | NSCLC         | Yes        |
| LC-0712      |                   43 | 70-79       | Spain        | SCLC          | Yes        |
| LC-1938      |                   44 | 60-69       | Philippines  | NSCLC         | No         |
| LC-0914      |                   44 | 70-79       | USA          | NSCLC         | No         |
| LC-1476      |                   44 | 50-59       | Indonesia    | NSCLC         | No         |
| LC-0235      |                   44 | 50-59       | Mongolia     | NSCLC         | Yes        |
| LC-1745      |                   45 | 50-59       | Kuwait       | NSCLC         | No         |
| LC-1740      |                   46 | 50-59       | Malaysia     | SCLC          | No         |
| LC-0853      |                   46 | 60-69       | Mexico       | NSCLC         | No         |
| LC-0645      |                   48 | 60-69       | Singapore    | NSCLC         | No         |
| LC-1124      |                   50 | 60-69       | Spain        | NSCLC         | Yes        |
| LC-0137      |                   53 | 60-69       | Bangladesh   | NSCLC         | No         |
| LC-0243      |                   56 | 60-69       | Turkey       | NSCLC         | No         |