<a href="https://colab.research.google.com/github/MiguelFigueroa02/MCPI_Student_Repo/blob/main/courses/1-Semester/fundamentals%20of%20statistics/Projects/Notebooks/Estad%C3%ADstica_Descriptiva_Visualizaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
  <img src="https://raw.githubusercontent.com/MiguelFigueroa02/MCPI_Student_Repo/refs/heads/main/images/logo.png"
       width="30%">
</p>

#Fundamentos de Estadística
---
**Profesor:** Dr. Daniel de La Rosa Gómez\
**Estudiante:** Miguel Figueroa Aguilar

## Estadística Descriptiva
---

### Nombre y Fuente:
---
En este caso elegí el Dataset relacionado con el cáncer de pulmón de pacientes de 60 países compartido en la plataforma de [Kaggle](https://www.kaggle.com/datasets/laxmikantaroy/lung-cancer-risk-factors-and-survival-dataset/data)\
Este agrupa información clínica, demográfica, genética y del diagnóstico y estilo de vida relacionada con el cáncer de pulmón.

### ¿Qué representan los datos?
---

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import plotly.express as px

In [2]:
#Establecemos un formato adecuado de visualización de los dataframe que extraigamos
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth',None)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

In [4]:
# El dataset se extrae de la plataforma de kaggle y se sube a un repositorio personal de github
url = 'https://raw.githubusercontent.com/MiguelFigueroa02/MCPI_Student_Repo/refs/heads/main/courses/1-Semester/fundamentals%20of%20statistics/Projects/Data/lung_cancer_dataset.csv'

response = requests.get(url)
if response.status_code == 200:
  print('Se accedió a dataset con éxito')
  df = pd.read_csv(url)

Se accedió a dataset con éxito

In [5]:
df.head()

,Patient_ID,Diagnosis_Year,Diagnosis_Date,WHO_Region,Country,Age,Age_Group,Gender,Smoking_Status,Cigarettes_Per_Day,Years_Smoking,Pack_Years,Secondhand_Smoke,Family_History,Occupational_Hazard,Air_Pollution_Exposure,Alcohol_Use,BMI,BMI_Category,Exercise_Frequency,Chronic_Lung_Disease,Asbestos_Exposure,Radon_Exposure,Previous_Cancer_History,Risk_Factor_Count,Genetic_Mutation,Coughing,Shortness_of_Breath,Chest_Pain,Coughing_Blood,Fatigue,Weight_Loss,Wheezing,Recurrent_Infections,Swallowing_Difficulty,Finger_Clubbing,Symptom_Count,Cancer_Type,NSCLC_Subtype,Cancer_Stage,Tumor_Size_cm,Metastasis,Diagnosis_Method,Treatment,Survival_Months,Survived
0,LC-0001,2020,2020-11-04,Western Pacific,China,46,40-49,Female,Current Smoker,28,28,39.20,Yes,No,No,Moderate,No Alcohol,29.60,Overweight,Low,Yes,No,No,No,2,No Mutation,Yes,Yes,Yes,No,No,Yes,No,No,Yes,No,5,NSCLC,Adenocarcinoma,Stage IV,6.40,Yes,MRI,Chemo + Radiation,4,No
1,LC-0002,2021,2021-12-09,Americas,Mexico,71,70-79,Male,Former Smoker,5,34,8.50,Yes,No,No,High,Heavy,31.30,Obese,Moderate,No,No,No,Yes,3,KRAS,Yes,Yes,No,No,Yes,No,Yes,No,Yes,No,5,NSCLC,Adenocarcinoma,Stage I,2.60,No,Biopsy,Surgery + Chemotherapy,76,Yes
2,LC-0003,2017,2017-04-05,Western Pacific,Japan,53,50-59,Female,Never Smoked,0,0,0.00,Yes,No,No,High,Moderate,25.80,Overweight,Low,No,No,No,No,2,KRAS,No,No,Yes,Yes,Yes,No,No,No,No,No,3,NSCLC,Squamous Cell,Stage I,2.90,No,LDCT Screening,Surgery,69,No
3,LC-0004,2018,2018-11-24,Western Pacific,Singapore,55,50-59,Male,Current Smoker,21,34,35.70,No,Yes,No,Moderate,No Alcohol,25.30,Overweight,Low,Yes,No,No,No,2,No Mutation,Yes,No,No,Yes,Yes,Yes,Yes,Yes,No,No,6,NSCLC,Adenocarcinoma,Stage IV,7.00,Yes,CT Scan,Chemotherapy,9,No
4,LC-0005,2024,2024-02-19,Western Pacific,Malaysia,54,50-59,Male,Never Smoked,0,0,0.00,No,No,Yes,High,No Alcohol,32.00,Obese,Low,Yes,No,No,Yes,4,KRAS,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,5,NSCLC,Adenocarcinoma,Stage III,5.80,No,Bronchoscopy,Immunotherapy,5,Yes

In [6]:
column_names = [f'`{column}`' for column in df.columns]
column_types = [f'`{df[column].dtype}`' for column in df.columns]
column_shapes = [len(df[column]) for column in df.columns]
column_na = [df[column].isna().sum() for column in df.columns]

In [8]:
df_analysis = pd.DataFrame({
    'Columna': column_names,
    'Tipos':column_types,
    'Num_Registros': column_shapes,
    })
# df_analysis.to_markdown()

|    | Columna                   | Tipos     |   Num_Registros |
|---:|:--------------------------|:----------|----------------:|
|  0 | `Patient_ID`              | `object`  |            2000 |
|  1 | `Diagnosis_Year`          | `int64`   |            2000 |
|  2 | `Diagnosis_Date`          | `object`  |            2000 |
|  3 | `WHO_Region`              | `object`  |            2000 |
|  4 | `Country`                 | `object`  |            2000 |
|  5 | `Age`                     | `int64`   |            2000 |
|  6 | `Age_Group`               | `object`  |            2000 |
|  7 | `Gender`                  | `object`  |            2000 |
|  8 | `Smoking_Status`          | `object`  |            2000 |
|  9 | `Cigarettes_Per_Day`      | `int64`   |            2000 |
| 10 | `Years_Smoking`           | `int64`   |            2000 |
| 11 | `Pack_Years`              | `float64` |            2000 |
| 12 | `Secondhand_Smoke`        | `object`  |            2000 |
| 13 | `Family_History`          | `object`  |            2000 |
| 14 | `Occupational_Hazard`     | `object`  |            2000 |
| 15 | `Air_Pollution_Exposure`  | `object`  |            2000 |
| 16 | `Alcohol_Use`             | `object`  |            2000 |
| 17 | `BMI`                     | `float64` |            2000 |
| 18 | `BMI_Category`            | `object`  |            2000 |
| 19 | `Exercise_Frequency`      | `object`  |            2000 |
| 20 | `Chronic_Lung_Disease`    | `object`  |            2000 |
| 21 | `Asbestos_Exposure`       | `object`  |            2000 |
| 22 | `Radon_Exposure`          | `object`  |            2000 |
| 23 | `Previous_Cancer_History` | `object`  |            2000 |
| 24 | `Risk_Factor_Count`       | `int64`   |            2000 |
| 25 | `Genetic_Mutation`        | `object`  |            2000 |
| 26 | `Coughing`                | `object`  |            2000 |
| 27 | `Shortness_of_Breath`     | `object`  |            2000 |
| 28 | `Chest_Pain`              | `object`  |            2000 |
| 29 | `Coughing_Blood`          | `object`  |            2000 |
| 30 | `Fatigue`                 | `object`  |            2000 |
| 31 | `Weight_Loss`             | `object`  |            2000 |
| 32 | `Wheezing`                | `object`  |            2000 |
| 33 | `Recurrent_Infections`    | `object`  |            2000 |
| 34 | `Swallowing_Difficulty`   | `object`  |            2000 |
| 35 | `Finger_Clubbing`         | `object`  |            2000 |
| 36 | `Symptom_Count`           | `int64`   |            2000 |
| 37 | `Cancer_Type`             | `object`  |            2000 |
| 38 | `NSCLC_Subtype`           | `object`  |            2000 |
| 39 | `Cancer_Stage`            | `object`  |            2000 |
| 40 | `Tumor_Size_cm`           | `float64` |            2000 |
| 41 | `Metastasis`              | `object`  |            2000 |
| 42 | `Diagnosis_Method`        | `object`  |            2000 |
| 43 | `Treatment`               | `object`  |            2000 |
| 44 | `Survival_Months`         | `int64`   |            2000 |
| 45 | `Survived`                | `object`  |            2000 |

In [11]:
df.describe()

,Diagnosis_Year,Age,Cigarettes_Per_Day,Years_Smoking,Pack_Years,BMI,Risk_Factor_Count,Symptom_Count,Tumor_Size_cm,Survival_Months
count,"2,000.00","2,000.00","2,000.00","2,000.00","2,000.00","2,000.00","2,000.00","2,000.00","2,000.00","2,000.00"
mean,"2,021.26",60.75,7.27,8.12,8.93,26.54,1.71,3.34,4.55,31.76
std,3.28,10.34,11.67,12.68,16.43,4.05,1.08,1.62,2.37,23.84
min,"2,015.00",30.00,0.00,0.00,0.00,16.00,0.00,0.00,0.50,1.00
25%,"2,019.00",53.00,0.00,0.00,0.00,23.80,1.00,2.00,2.60,11.00
50%,"2,022.00",60.00,0.00,0.00,0.00,26.50,2.00,3.00,4.30,26.00
75%,"2,024.00",68.00,14.00,16.00,12.00,29.32,2.00,4.00,6.20,49.00
max,"2,026.00",89.00,56.00,59.00,106.00,40.00,6.00,9.00,13.30,110.00

In [14]:
df.describe(exclude='number')

,Patient_ID,Diagnosis_Date,WHO_Region,Country,Age_Group,Gender,Smoking_Status,Secondhand_Smoke,Family_History,Occupational_Hazard,Air_Pollution_Exposure,Alcohol_Use,BMI_Category,Exercise_Frequency,Chronic_Lung_Disease,Asbestos_Exposure,Radon_Exposure,Previous_Cancer_History,Genetic_Mutation,Coughing,Shortness_of_Breath,Chest_Pain,Coughing_Blood,Fatigue,Weight_Loss,Wheezing,Recurrent_Infections,Swallowing_Difficulty,Finger_Clubbing,Cancer_Type,NSCLC_Subtype,Cancer_Stage,Metastasis,Diagnosis_Method,Treatment,Survived
count,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000
unique,2000,1520,6,60,6,2,3,2,2,2,3,3,4,3,2,2,2,2,10,2,2,2,2,2,2,2,2,2,2,2,4,4,2,7,8,2
top,LC-1984,2026-07-07,Western Pacific,Japan,50-59,Male,Never Smoked,No,No,No,Moderate,Moderate,Overweight,Low,No,No,No,No,No Mutation,No,No,No,No,Yes,No,No,No,No,No,NSCLC,Adenocarcinoma,Stage I,No,CT Scan,Surgery,No
freq,1,8,631,74,657,1248,1311,1050,1483,1572,766,811,876,772,1624,1886,1847,1881,729,1024,1134,1292,1544,1323,1333,1448,1403,1717,1752,1771,1109,577,1441,590,410,1244